### ISSUE TITLE
Parse title hints into something structured.

### ISSUE THREAD

**Issue by thisismattmiller** [nypl-registry/serialization-shadowcat#1]
[microform] = ?
[electronic resource] = ?

**Comment by saverkamp** [comment]
Do records with 245$h = [microform] not have a material type code, or were you wanting to use this for something else?

**Comment by thisismattmiller** [comment]
Yes you are right:
http://45.55.205.23/api/bnumber/11488797

But right now we are mapping that to resource type txt:
https://github.com/nypl-registry/utils-lexicon/blob/master/lib/maps/catalog_material_type.js

Because there is no microfilm type in http://id.loc.gov/vocabulary/resourceTypes.html ?

**Comment by saverkamp** [comment]
Right, because it's the type of content of the material, not the carrier (for the most part). We're just guessing that the bulk of microfilm will be text.

**Comment by thisismattmiller** [comment]
Yeah, so I want to do something else with it so we can facet on it.

**Comment by saverkamp** [comment]
Maybe time to introduce Form into our vocab. We skipped it in the initial mapping because we were trying to keep it simple. But we passed simple long ago, so...

I can start looking at controlled vocabularies for this. We'll probably use dcterms:format

**Comment by thisismattmiller** [comment]
We have form in our terms, here are all the used fast:form we have right now, mostly from worldcat enrichment:

[current_forms.txt](https://github.com/nypl-registry/serialization-shadowcat/files/230675/current_forms.txt)

**Comment by saverkamp** [comment]
I think we need a more controlled list for physical form. That list is mostly genre terms (ex. "Pirate films", "Honky-tonk music", "Thumb Bibles")

**Comment by thisismattmiller** [comment]
It does stray into physical form though, "Texts", "Facsimiles", "Catalogs" but yeah, smaller physical form would be better. Strange FAST does not have microfilm as a form.

**Comment by saverkamp** [comment]
Guessing the bulk is coming from LCGFT (http://id.loc.gov/authorities/genreForms.html) which defines Form as " a characteristic of works with a particular format and/or purpose" such as "shorts" or "animation." LCGFT "Genre refers to categories of works that are characterized by similar plots, themes, settings, situations, and characters. Examples of genres are westerns and thrillers. " 

In MMS/MODS we put LCGFT "Form" terms in "Genre" and we don't even really deal with LCGFT Genre terms. (not sure why the low uptake in digital libraries.) In MODS Form, we capture the physical form, or carrier of the content, like "Microforms" or "Video tapes". It's all very fuzzy and confusing and many papers have been written on the topic, which is why it's hard to generate controlled lists for any of these concepts that will also be useful for faceting.

**Comment by thisismattmiller** [comment]
Okay, back to the original idea. I'm really not trying to make a form for everything. Right now I'm just after:

```
+-Nice-Facet-Box-+
|                |
|[x] Microfilm   |
|[x] Is Online   |
|                |
+----------------+
```

Meaning if it is microfilm it needs to have a structured flag and if it is somehow online [electronic resource] or in DC/Hathi it can be faceted. Probably a few others will emerge but that is all I can think of now.

**Comment by saverkamp** [comment]
What about something like this to start, just to take care of this immediate use case. A new local terms scheme called "NYPLFormat" with these two terms to start, "Microfilm" and "Electronic resources"

Using dcterms:format as the predicate.

@prefix skos: http://www.w3.org/2004/02/skos/core# .
@prefix terms: http://data.nypl.org/terms# .

http://data.nypl.org/terms/000000000 a skos:Concept ;
    skos:prefLabel "Microfilm" ;
    skos:altLabel "Microforms" ;
    skos:inScheme terms:NYPLFormat ;
    skos:closeMatch "http://id.loc.gov/vocabulary/graphicMaterials/tgm006502" .

http://data.nypl.org/terms/1111111111 a skos:Concept ;
    skos:prefLabel "Electronic resources" ;
    skos:inScheme terms:NYPLFormat .

I wouldn't apply this to physical items that have corresponding image in DC, though.

**Comment by thisismattmiller** [comment]
That looks great. But we need something that can be applied to collections/components/items that have captures. It doesn't make sense that a online facet would not also include things in DC.

**Comment by saverkamp** [comment]
But you can derive if something is in DC through application logic, correct? We have that (tentative) dcFlag in the Capture data. This feels like a case of display driving data modeling, which I'm uneasy about. What is this facet box supposed to represent? "Is online" and "Microfilm" are options for ... ?

**Comment by thisismattmiller** [comment]
I don't understand, it is a facet box, to facet search results. It's fine it can live in the application layer. But I don't see the problem with a data flag giving the heads up that this collection contains digital content. I know for sure if I was working with our data via API/data dump I would hate to have to parse every child looking for a capture just to know if a collection has digital content. And if it is going to be in the API/data dump it needs to be modeled, the whole point of this issue. It seems like a simple and convenient thing to have that doesn't really effect the RWO model at all...

**Comment by saverkamp** [comment]
Split this into two issues:
- Define property and term(s) for identifying microfilm
- Define property for flagging resources as having online content.
